### ISSUE TITLE
'convert model error' when converting SNLI rnn_matching.yml to TFLITE

### ISSUE THREAD

**Issue by jipson7** [didi/delta#177]
Thank you for the very useful project.

**Describe the bug**

A simple error is thrown when trying to convert the snli model to tflite.

The error is:

```

Params:
stage: -1 - 100
TARGET: linux
ARCH: x86_64
INPUT_MODEL: /user/caleb.p/Development/delta/./dpl/model
INPUT_YAML: /user/caleb.p/Development/delta/./dpl/model/model.yaml
OUTPUT_MODEL: /user/caleb.p/Development/delta/./dpl/.gen


Input: /user/caleb.p/Development/delta/./dpl/model
Output: /user/caleb.p/Development/delta/./dpl/.gen

Convert model...
~/Development/delta/dpl/gadapter ~/Development/delta/dpl
OUTPUT_NUM: 2
OUTPUT_NAMES: ,ArgMax:0,score:0
Satrt transform graph ...
tflite to be added.
convert model error
```

**To Reproduce**
1. Follow the steps in docs to train_and_eval the snli model with the config located at `delta/egs/snli/match/v1/config/rnn_match.yml`
2. move the saved model to the dpl/model folder as instructed.
3. Use the following model.yaml to convert the model

```
model:
  custom_ops_path: "../dpl/output/lib/custom_ops/libx_ops.so" 
  graphs:
    -
      # meta data
      id: 0
      name: "snli_encoder" # model name

      # deltann type
      server_type: "local" # local, remote
      engine: "TFLITE" # TF, TFLITE, TFTRT, TFSERVING

      # model config
      version: 1    # model version
      local:  # local run
        path: "../dpl/output/model/saved_model" # model path without version info
        model_type: "saved_model" # e.g. saved_model, frozen_graph_pb, frozen_graph_txt
      # inputs and outputs
      inputs:
        -
          id: 0
          name: "input_sent_left:0"
          shape: [-1]
          dtype: "string"
        -
          id: 1
          name: "input_sent_right:0"
          shape: [-1]
          dtype: "string"
      outputs:
        -
          id: 0
          name: "ArgMax:0"
          shape: [-1]
          dtype: "int64"
        -
          id: 1
          name: "score:0"
          shape: [-1, 3]
          dtype: "float"


runtime:
  num_threads: 20

serving:
  max_worker: 5
  max_queue: 100
```

4. run ./run.sh located in dpl

**Expected behavior**
Deployment artifacts to be created in output folder

**Desktop (please complete the following information):**
 - OS:  Ubuntu 18.04
